<%@ Page Title="About" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.vb" Inherits="Final_Project.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h1> About</h1>
    <h3>This site is desgined to allow students to find the chairs of thier majors and other students in thier majors</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pharetra aliquet tristique. Nunc pulvinar dignissim felis, at mattis dui condimentum eu. Nam est libero, sollicitudin at sapien mattis, placerat laoreet magna. Nullam faucibus pharetra leo mattis blandit. Suspendisse sodales suscipit justo, a hendrerit magna porta et. Nam fermentum pretium dolor, at finibus leo sagittis in. Nunc sed elit sit amet magna sodales viverra at ac eros. Quisque vulputate nibh tortor, pharetra cursus mi sodales quis. Suspendisse eget tempus mauris, sed interdum tortor.</p>
    <p>Phasellus feugiat libero quis dignissim egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae sem a odio blandit feugiat. Sed nec massa id magna dictum pulvinar. Vestibulum quis gravida nulla. Mauris est erat, dictum id ultricies et, viverra ac ligula. Proin vestibulum, ante elementum mollis efficitur, magna lacus varius nulla, non condimentum neque lorem et risus. Aliquam dignissim, magna sit amet placerat placerat, nulla tortor aliquam mauris, ut ultricies justo elit nec dolor. Aliquam non gravida leo, sit amet tempor ex. Integer consectetur lacus id feugiat imperdiet. Pellentesque metus arcu, luctus eu erat vel, suscipit iaculis metus.</p>
    <p>Maecenas ullamcorper pharetra nibh at tincidunt. Ut nec dolor diam. Ut hendrerit id elit et malesuada. Quisque eu purus et felis lobortis volutpat. Duis urna tellus, fringilla quis arcu eu, lobortis sodales justo. Integer mollis augue a lectus volutpat, non egestas tellus ullamcorper. Praesent orci mauris, interdum ac semper ac, mollis ut ante. Suspendisse bibendum, lectus vel hendrerit maximus, magna libero elementum sapien, et scelerisque ex urna pretium metus. Vivamus aliquet pretium venenatis. Aenean ex erat, commodo sit amet gravida sit amet, elementum vitae ante.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut nibh vel magna sodales hendrerit et sed sem. Suspendisse convallis maximus quam, in tempus velit. Mauris eleifend interdum mi, et feugiat nibh viverra et. Ut quis accumsan turpis, quis sodales libero. Ut quis odio ligula. Proin viverra ipsum ut nulla consectetur dapibus. Aliquam cursus convallis nisl et pharetra.</p>
    <p>Sed non tincidunt enim. Curabitur rutrum auctor dictum. Sed non quam a velit viverra imperdiet. Integer nec eros lobortis purus tempor vulputate ut tempus est. Maecenas nunc dolor, tincidunt ac commodo eu, venenatis a odio. Duis ut rutrum elit. Fusce nisl sem, mattis vel efficitur ac, ornare sagittis mauris. Fusce ornare euismod tempor. Nulla justo nisl, ultricies in purus sed, semper interdum odio. Mauris sit amet posuere felis, tincidunt imperdiet ipsum. Fusce ac arcu non libero gravida blandit nec eu enim.</p>
    <p>Praesent bibendum sapien at tincidunt viverra. Nam et ex orci. Vivamus eleifend lectus interdum pellentesque tincidunt. Cras suscipit laoreet pulvinar. Nam nec imperdiet risus. Donec eleifend nisi et vehicula blandit. Donec purus nisl, interdum ut nisl ut, sodales fermentum nulla. Vestibulum purus enim, ullamcorper non augue vel, pretium placerat lectus. Nulla facilisi. Fusce sit amet nibh pretium, faucibus mauris non, faucibus felis. Nam eget risus turpis. Morbi ac ipsum non ipsum lacinia varius at a elit. Suspendisse mollis vitae lectus et consequat. Donec posuere mattis risus, in rutrum ex.</p>
</asp:Content>
